import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto, Poppins } from "next/font/google";
import theme from "../theme";
import { NextAppProvider } from "@toolpad/core/nextjs";
import DashboardIcon from "@mui/icons-material/Dashboard";
import ShoppingCartIcon from "@mui/icons-material/ShoppingCart";
import CallIcon from "@mui/icons-material/Call";
import CallMadeIcon from "@mui/icons-material/CallMade";
import CallReceivedIcon from "@mui/icons-material/CallReceived";
import Chip from "@mui/material/Chip";
import PersonIcon from "@mui/icons-material/Person";
import { connectDb } from "@/database/config/db";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectDb();
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body className={`${roboto.variable} ${poppins.variable} antialiased`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <NextAppProvider
            theme={theme}
            navigation={[
              {
                segment: "dashboard",
                title: "Dashboard",
                icon: <DashboardIcon />,
              },
              {
                segment: "orders",
                title: "Orders",
                icon: <ShoppingCartIcon />,
                pattern: "orders{/:orderId}*",
              },
              {
                segment: "contacts",
                title: "Contacts",
                icon: <PersonIcon />,
                action: <Chip label={7} color="primary" size="small" />,
              },
              {
                segment: "calls",
                title: "Calls",
                icon: <CallIcon />,
                children: [
                  {
                    segment: "made",
                    title: "Made",
                    icon: <CallMadeIcon />,
                    action: <Chip label={12} color="success" size="small" />,
                  },
                  {
                    segment: "received",
                    title: "Received",
                    icon: <CallReceivedIcon />,
                    action: <Chip label={4} color="error" size="small" />,
                  },
                ],
              },
            ]}
          >
            {children}
          </NextAppProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

